from sqlalchemy import Column, Integer, String, Float, DateTime, Text, Boolean
from core.database import Base
from datetime import datetime

class Patient(Base):
    __tablename__ = "patients"
    id = Column(Integer, primary_key=True, index=True)
    custom_id = Column(String, unique=True, index=True, nullable=True)
    name = Column(String)
    email = Column(String, unique=True)
    password = Column(String)
    role = Column(String, default="patient")
    phone = Column(String)
    gender = Column(String)
    age = Column(Integer)
    dob = Column(String)
    home_address = Column(String)
    area = Column(String)
    district = Column(String)
    state = Column(String)
    pincode = Column(String)
    referral_code = Column(String, unique=True, nullable=True)
    profile_image = Column(Text, nullable=True)
    status = Column(String, default="Active")
    verification_status = Column(String, default="Pending")
    created_at = Column(DateTime, default=datetime.utcnow)
    last_login = Column(DateTime, nullable=True)

class Doctor(Base):
    __tablename__ = "doctors"
    id = Column(Integer, primary_key=True, index=True)
    custom_id = Column(String, unique=True, index=True, nullable=True)
    name = Column(String)
    email = Column(String, unique=True)
    password = Column(String)
    role = Column(String, default="doctor")
    phone = Column(String)
    gender = Column(String)
    age = Column(Integer)
    dob = Column(String)
    home_address = Column(String)
    area = Column(String)
    district = Column(String)
    state = Column(String)
    pincode = Column(String)
    hospital = Column(String, nullable=True)
    specialisation = Column(String, nullable=True)
    qualification = Column(String, nullable=True)
    experience = Column(String, nullable=True)
    referral_code = Column(String, unique=True, nullable=True)
    profile_image = Column(Text, nullable=True)
    status = Column(String, default="Active")
    verification_status = Column(String, default="Pending")
    created_at = Column(DateTime, default=datetime.utcnow)
    last_login = Column(DateTime, nullable=True)

class Distributor(Base):
    __tablename__ = "distributors"
    id = Column(Integer, primary_key=True, index=True)
    custom_id = Column(String, unique=True, index=True, nullable=True)
    name = Column(String)
    email = Column(String, unique=True)
    password = Column(String)
    role = Column(String, default="distributor")
    phone = Column(String)
    gender = Column(String)
    age = Column(Integer)
    dob = Column(String)
    home_address = Column(String)
    area = Column(String)
    district = Column(String)
    state = Column(String)
    pincode = Column(String)
    company_name = Column(String, nullable=True)
    business_type = Column(String, nullable=True)
    distributor_type = Column(String, nullable=True)
    license_number = Column(String, nullable=True)
    referral_code = Column(String, unique=True, nullable=True)
    profile_image = Column(Text, nullable=True)
    status = Column(String, default="Active")
    verification_status = Column(String, default="Pending")
    created_at = Column(DateTime, default=datetime.utcnow)
    last_login = Column(DateTime, nullable=True)

class AdminStaff(Base):
    __tablename__ = "admin_staff"
    id = Column(Integer, primary_key=True, index=True)
    custom_id = Column(String, unique=True, index=True, nullable=True)
    name = Column(String)
    email = Column(String, unique=True)
    password = Column(String)
    role = Column(String, default="admin") # "admin" or "sub_admin"
    phone = Column(String)
    gender = Column(String)
    age = Column(Integer)
    dob = Column(String)
    home_address = Column(String)
    area = Column(String)
    district = Column(String)
    state = Column(String)
    pincode = Column(String)
    permissions = Column(Text, nullable=True) # JSON string of permissions
    profile_image = Column(Text, nullable=True)
    status = Column(String, default="Active")
    verification_status = Column(String, default="Approved")
    created_at = Column(DateTime, default=datetime.utcnow)
    last_login = Column(DateTime, nullable=True)

class SuperAdmin(Base):
    __tablename__ = "super_admins"
    id = Column(Integer, primary_key=True, index=True)
    custom_id = Column(String, unique=True, index=True, nullable=True)
    name = Column(String)
    email = Column(String, unique=True)
    password = Column(String)
    role = Column(String, default="super_admin")
    phone = Column(String)
    gender = Column(String)
    age = Column(Integer)
    dob = Column(String)
    home_address = Column(String)
    area = Column(String)
    district = Column(String)
    state = Column(String)
    pincode = Column(String)
    profile_image = Column(Text, nullable=True)
    status = Column(String, default="Active")
    verification_status = Column(String, default="Approved")
    created_at = Column(DateTime, default=datetime.utcnow)
    last_login = Column(DateTime, nullable=True)
